package com.couple.translator.core.navigation

enum class Screen(val route: String) {
    Login("login"),
    Register("register"),
    ForgotPassword("forgot_password"),

    Main("main"),

    Home("home"),
    Mailbox("mailbox"),
    AiChat("ai_chat"),

    Profile("profile"),
    CoupleBind("couple_bind"),
    CoupleInfo("couple_info"),
    QuestionnaireIntro("questionnaire_intro"),
    Questionnaire("questionnaire"),
    QuestionnaireResult("questionnaire_result"),
    QuestionnaireHistory("questionnaire_history"),
    ProfileResult("profile_result"),
    CoupleProfile("couple_profile"),
    AiSessionList("ai_session_list"),
    LetterList("letter_list"),
    LetterDetail("letter_detail"),
    ComposeLetter("compose_letter"),
    ColdWar("cold_war"),
    MediationInvite("mediation_invite"),
    MediationInput("mediation_input"),
    MediationConfirm("mediation_confirm"),
    MediationResult("mediation_result"),
    MediationExplanation("mediation_explanation"),
    Memory("memory"),
    DualPerspectiveList("dual_perspective_list"),
    DualPerspectiveDetail("dual_perspective_detail"),
    CreateDualEvent("create_dual_event"),
    SubmitDualRecord("submit_dual_record"),
    Museum("museum"),
    MuseumItemDetail("museum_item_detail"),
    AddMuseumItem("add_museum_item"),
    PracticeList("practice_list"),
    PracticeDetail("practice_detail"),
    PracticeResult("practice_result"),
    AnniversaryList("anniversary_list"),
    AddAnniversary("add_anniversary"),
    Wishlist("wishlist"),
    AddWishlist("add_wishlist"),
    AvatarCustomize("avatar_customize"),

    // 单身模式专属
    DiaryList("diary_list"),
    DiaryDetail("diary_detail"),
    ComposeDiary("compose_diary"),
}
