"""add_timestamps_to_models

Revision ID: 0b03d8a0b9cd
Revises: f1a2b3c4d5e6
Create Date: 2026-06-20 18:04:34.148884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b03d8a0b9cd'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('ai_knowledge_chunk', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_knowledge_chunk_doc_id')

    with op.batch_alter_table('ai_memory', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_memory_relation_id')
        batch_op.drop_index('ix_ai_memory_user_id')

    with op.batch_alter_table('couple_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couple_profile', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('ai_memory', schema=None) as batch_op:
        batch_op.create_index('ix_ai_memory_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_ai_memory_relation_id', ['relation_id'], unique=False)

    with op.batch_alter_table('ai_knowledge_chunk', schema=None) as batch_op:
        batch_op.create_index('ix_ai_knowledge_chunk_doc_id', ['doc_id'], unique=False)

    with op.batch_alter_table('ai_chat_message', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
