"""add_v1_1_questionnaire_profile_ai

Revision ID: 91202fedb2f5
Revises: ac1c5929e597
Create Date: 2026-06-20 16:15:08.102677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91202fedb2f5'
down_revision: Union[str, None] = 'ac1c5929e597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_scene',
    sa.Column('scene_key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_key')
    )
    op.create_table('psychology_model',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionnaire',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_prompt_template',
    sa.Column('scene_key', sa.String(length=50), nullable=False),
    sa.Column('template_content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scene_key'], ['ai_scene.scene_key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionnaire_question',
    sa.Column('questionnaire_id', sa.BigInteger(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('dimension_key', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaire.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationship_profile',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('questionnaire_id', sa.BigInteger(), nullable=False),
    sa.Column('profile_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaire.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_chat_session',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('relation_id', sa.BigInteger(), nullable=False),
    sa.Column('scene_key', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('privacy_level', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['relation_id'], ['couple_relation.id'], ),
    sa.ForeignKeyConstraint(['scene_key'], ['ai_scene.scene_key'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_prompt_version',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('relation_id', sa.BigInteger(), nullable=False),
    sa.Column('scene_key', sa.String(length=50), nullable=False),
    sa.Column('prompt_content', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['relation_id'], ['couple_relation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('couple_profile',
    sa.Column('relation_id', sa.BigInteger(), nullable=False),
    sa.Column('user_a_profile_id', sa.BigInteger(), nullable=False),
    sa.Column('user_b_profile_id', sa.BigInteger(), nullable=False),
    sa.Column('conflict_pattern', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['relation_id'], ['couple_relation.id'], ),
    sa.ForeignKeyConstraint(['user_a_profile_id'], ['relationship_profile.id'], ),
    sa.ForeignKeyConstraint(['user_b_profile_id'], ['relationship_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_dimension_score',
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('dimension_key', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['relationship_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionnaire_answer',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('questionnaire_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('answer_value', sa.JSON(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questionnaire_question.id'], ),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaire.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'questionnaire_id', 'question_id', name='uq_user_questionnaire_question')
    )
    op.create_table('questionnaire_option',
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('option_text', sa.String(length=500), nullable=False),
    sa.Column('score_value', sa.Float(), nullable=False),
    sa.Column('dimension_delta', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questionnaire_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_chat_message',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_output', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.String(length=30), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_chat_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_output_feedback',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback_tag', sa.String(length=50), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['ai_chat_message.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_output_feedback')
    op.drop_table('ai_chat_message')
    op.drop_table('questionnaire_option')
    op.drop_table('questionnaire_answer')
    op.drop_table('profile_dimension_score')
    op.drop_table('couple_profile')
    op.drop_table('ai_prompt_version')
    op.drop_table('ai_chat_session')
    op.drop_table('relationship_profile')
    op.drop_table('questionnaire_question')
    op.drop_table('ai_prompt_template')
    op.drop_table('questionnaire')
    op.drop_table('psychology_model')
    op.drop_table('ai_scene')
    # ### end Alembic commands ###
