"""v1.4_add_dual_perspective_museum_practice_anniversary_wishlist

Revision ID: e85adae883dc
Revises: b2c3d4e5f6a7
Create Date: 2026-06-20 17:13:56.731393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e85adae883dc'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationship_practice',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('practice_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('practice_type')
    )
    op.create_table('anniversary',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('relation_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['relation_id'], ['couple_relation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anniversary', schema=None) as batch_op:
        batch_op.create_index('ix_anniversary_relation_id', ['relation_id'], unique=False)

    op.create_table('dual_perspective_event',
    sa.Column('relation_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['relation_id'], ['couple_relation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dual_perspective_event', schema=None) as batch_op:
        batch_op.create_index('ix_dpe_relation_id', ['relation_id'], unique=False)
        batch_op.create_index('ix_dpe_status', ['status'], unique=False)

    op.create_table('museum_item',
    sa.Column('relation_id', sa.BigInteger(), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['relation_id'], ['couple_relation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('museum_item', schema=None) as batch_op:
        batch_op.create_index('ix_museum_item_type', ['item_type'], unique=False)
        batch_op.create_index('ix_museum_pinned', ['pinned'], unique=False)
        batch_op.create_index('ix_museum_relation_id', ['relation_id'], unique=False)

    op.create_table('practice_record',
    sa.Column('practice_id', sa.BigInteger(), nullable=False),
    sa.Column('relation_id', sa.BigInteger(), nullable=False),
    sa.Column('initiator_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['initiator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['relationship_practice.id'], ),
    sa.ForeignKeyConstraint(['relation_id'], ['couple_relation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_record', schema=None) as batch_op:
        batch_op.create_index('ix_practice_record_initiator_id', ['initiator_id'], unique=False)
        batch_op.create_index('ix_practice_record_practice_id', ['practice_id'], unique=False)
        batch_op.create_index('ix_practice_record_relation_id', ['relation_id'], unique=False)

    op.create_table('wishlist',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('relation_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['relation_id'], ['couple_relation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.create_index('ix_wishlist_relation_id', ['relation_id'], unique=False)
        batch_op.create_index('ix_wishlist_status', ['status'], unique=False)

    op.create_table('dual_perspective_record',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['dual_perspective_event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dual_perspective_record', schema=None) as batch_op:
        batch_op.create_index('ix_dpr_event_id', ['event_id'], unique=False)
        batch_op.create_index('ix_dpr_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dual_perspective_record', schema=None) as batch_op:
        batch_op.drop_index('ix_dpr_user_id')
        batch_op.drop_index('ix_dpr_event_id')

    op.drop_table('dual_perspective_record')
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_index('ix_wishlist_status')
        batch_op.drop_index('ix_wishlist_relation_id')

    op.drop_table('wishlist')
    with op.batch_alter_table('practice_record', schema=None) as batch_op:
        batch_op.drop_index('ix_practice_record_relation_id')
        batch_op.drop_index('ix_practice_record_practice_id')
        batch_op.drop_index('ix_practice_record_initiator_id')

    op.drop_table('practice_record')
    with op.batch_alter_table('museum_item', schema=None) as batch_op:
        batch_op.drop_index('ix_museum_relation_id')
        batch_op.drop_index('ix_museum_pinned')
        batch_op.drop_index('ix_museum_item_type')

    op.drop_table('museum_item')
    with op.batch_alter_table('dual_perspective_event', schema=None) as batch_op:
        batch_op.drop_index('ix_dpe_status')
        batch_op.drop_index('ix_dpe_relation_id')

    op.drop_table('dual_perspective_event')
    with op.batch_alter_table('anniversary', schema=None) as batch_op:
        batch_op.drop_index('ix_anniversary_relation_id')

    op.drop_table('anniversary')
    op.drop_table('relationship_practice')
    # ### end Alembic commands ###
